repos:
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        name: black (py3.10)
        language_version: python3.10
      - id: black
        name: black (py3.11)
        language_version: python3.11
