name: Initial Repo Setup

on:
  push:
    branches: [main]

jobs:

  increment-version:
    runs-on: ubuntu-latest
    outputs:
      new-version: ${{ steps.run-increment-version.outputs.new-version }}
    steps:
      - name: Run the increment-version action
        id: run-increment-version
        uses: GenapsysInc/internal-actions/reusable-actions/increment-version@main
        with:
          json: repo-data.json
          token: ${{ secrets.GH_REST_API_TOKEN }}
  init-repo-settings:
    name: Run the initial repo configuration
    runs-on: ubuntu-latest
    steps:
      - uses: GenapsysInc/internal-actions/reusable-actions/repo-configuration@main
        with:
          initialize: true
          disable_action: true
          token: ${{ secrets.GH_REST_API_TOKEN }}